### ISSUE TITLE
Consider moving from `ncc` to `bun`

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/action-deploy-plugin#14]
`bun` is also capable to bundle and do one file compilation, much faster than `ncc`, with less artifacts, which could be considered to optimize our builds.

https://bun.sh/docs/bundler

**Comment by 0x4007** [comment]
> I think sadly `bun` bundling is still too immature, and I am running into bundling issues, such as this one:
> 
> https://github.com/oven-sh/bun/issues/14011
> 
> 
> 
> We might not be able to move to `bun` for now.

You should close these as unplanned
