### ISSUE TITLE
Generate a GPG key based on a Github App

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os/action-deploy-plugin#3]
There is currently no PGP key set to sign the commits. One should be generated from a new Github App.

**Comment by gentlementlegen** [comment]
@0x4007 It is not possible to use this system with Apps because apps do not have emails nor associate to a user. I believe you expect to use Octokit and authenticate as an app instead?

**Comment by 0x4007** [comment]
So when what is this spec about? Using a personal profile?

**Comment by gentlementlegen** [comment]
@0x4007 Either this or the usual Auth authentication with Octokit yes.

**Comment by gentlementlegen** [comment]
@0x4007  👍 for which option? 😄

**Comment by 0x4007** [comment]
Apps are always preferred.
